### PR TITLE
WIP: add relevant Goldacre recommendation

### PR DESCRIPTION
**Pull request by wbryant**
Completed addition of a recommendation directly related to open source tooling in the NHS (though it doesn't explicitly mention R).  Also updated the quote formatting in the README to be consistent.

### CODE REVIEW

**Comment by wbryant** [comment]
This is to add context from the Goldacre review calling for updates to IT policies on modern open tools.

**Comment by ChrisBeeley** [comment]
Looks good, ready for merge?

**Comment by wbryant** [comment]
Yes, I'm happy with it.

**Comment by wbryant** [comment]
Not aure if this will play nice with your latest draft revisions, but happy to rebase and revise if necessary?

**Pull request merged**
